### ISSUE TITLE
Crash on server with mc 1.20.1

### ISSUE THREAD

**Issue by ryleu** [TheDeathlyCow/frostiful#55]
```
christmas-modpack-2023-mc-1   | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'frostiful'!
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.0-launcher.0.11.2.jar:0.11.2]
christmas-modpack-2023-mc-1   | Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:49) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.createDefault(GsonConfigSerializer.java:92) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:86) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at com.github.thedeathlycow.frostiful.Frostiful.onInitialize(Frostiful.java:42) ~[frostiful-0.10.1.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         ... 7 more
christmas-modpack-2023-mc-1   | Caused by: java.lang.reflect.InvocationTargetException
christmas-modpack-2023-mc-1   |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
christmas-modpack-2023-mc-1   |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:47) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.createDefault(GsonConfigSerializer.java:92) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:86) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at com.github.thedeathlycow.frostiful.Frostiful.onInitialize(Frostiful.java:42) ~[frostiful-0.10.1.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         ... 7 more
christmas-modpack-2023-mc-1   | Caused by: java.lang.NoSuchFieldError: clientConfig
christmas-modpack-2023-mc-1   |         at com.github.thedeathlycow.frostiful.config.FrostifulConfig.<init>(FrostifulConfig.java:15) ~[frostiful-0.10.1.jar:?]
christmas-modpack-2023-mc-1   |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
christmas-modpack-2023-mc-1   |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:47) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.createDefault(GsonConfigSerializer.java:92) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:86) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-11.0.99-cbbb331fbbbb4708.jar:?]
christmas-modpack-2023-mc-1   |         at com.github.thedeathlycow.frostiful.Frostiful.onInitialize(Frostiful.java:42) ~[frostiful-0.10.1.jar:?]
christmas-modpack-2023-mc-1   |         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
christmas-modpack-2023-mc-1   |         ... 7 more
christmas-modpack-2023-mc-1   | 2023-12-08T02:39:21.322Z        INFO    mc-server-runner        Done
```
seems odd that it'd look for client config when running server-side, but here we are

**Comment by ryleu** [comment]
seems mostly to do with cloth config

**Comment by TheDeathlyCow** [comment]
Already found and fixed this issue [on dev](https://github.com/TheDeathlyCow/frostiful/commit/b7a965c8bec5da5fc207e093d421618cd20e706f) haha

**Comment by ryleu** [comment]
great! any eta on a release?

**Comment by TheDeathlyCow** [comment]
no more than a day or two now. the next release will be the 1.0 release so im working on some admin stuff, a couple of small integrations, and a trailer (which is basically done) so once thats all done itll be out.

**Comment by ryleu** [comment]
excellent, good to hear! working on my yearly christmas modpack, and i always love using frostiful. i'm happy to see you bring it to a full release! for now i've just compiled a jar from the dev branch
